### ISSUE TITLE
Localisation: French - France

### ISSUE THREAD

**Issue by jeanetienne** [brunophilipe/Cakebrew#145]
I can contribute localising the UI in French (France) as I am a native speaker.

**Comment by brunophilipe** [comment]
**[Download this file](https://www.cakebrew.com/resources/fr.xliff.zip)**

It is a single XLIFF file with all strings that need to be translated. You will notice some strings are already in French. That's because I used a tool that automatically translates the default Apple menu entries. It is important to keep them as they are, to keep a uniform experience with other OS X Apps.

I recommend using the [Brightec online XLIFF editor](http://xliff.brightec.co.uk) to edit this file, as it is an XML and they are quite annoying to edit by hand.

Please, take as much time as you need, there is no hurry. :smile:
And thanks for your interest!

**Comment by bfontaine** [comment]
@jeanetienne Are you working on it? I can help if that’s needed; I’m a native speaker too.

**Comment by jeanetienne** [comment]
I'm finished, just need to find time to build and check that everything make sense. Perhaps you could review my PR (when I get around pushing it :smile: )?

**Comment by bfontaine** [comment]
I’d be glad to review it. Thank you for your work!

**Comment by jeanetienne** [comment]
[fr.xliff.zip](https://github.com/brunophilipe/Cakebrew/files/134020/fr.xliff.zip)
Finally took the time to upload this. Sorry all for the long wait :disappointed: 
@bfontaine keen on reviewing this?
@brunophilipe I couldn't add it to the project through `Editor > Import Localizations...` in Xcode 7.2.1 (7C1002), any idea why?

Thanks :)

**Comment by bfontaine** [comment]
Great! I’ll take a look.

**Comment by bfontaine** [comment]
I tried to import it as well to no avail. The system log says:
```
Feb 17 21:49:50 mbf Xcode[44235]: [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-9548.1/IDEFoundation/Localization/IDELocalizationWork.m:487
	Details:  Failed to read strings file "/var/folders/0d/mmrjgs1n0zdfdr386xlnx61h0000gn/T/Xcode3SourceStringsAdaptor-1EE5964F-701C-4F74-8E9E-74D9F75CECC9/MoveApplication.strings", underlying error:
	The data couldn’t be read because it isn’t in the correct format.
	Object:   <Xcode3LocalizedSourceStringsAdaptorTableWorkContext: 0x7fb051664580>
	Method:   -work
	Thread:   <NSThread: 0x7fb043f178d0>{number = 1, name = main}
	Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
```

**Comment by bfontaine** [comment]
(sorry for the third comment in a row)

@jeanetienne Here are my review notes, in French: https://gist.github.com/bfontaine/6c376c40ed68f4e80e72
Most of them are questions because there’s almost never only one possible translation :smile:

**Comment by brunophilipe** [comment]
This is a problem with Xcode. Not even exporting an xliff file works...

**Comment by jeanetienne** [comment]
@bfontaine that was fast! Thanks for the feedback! I'll see if I still create a PR to collect feedback and progress, or perhaps just replies to your gist?
@brunophilipe I'll try with an earlier version of Xcode perhaps? When was the last version you know worked?

**Comment by bfontaine** [comment]
@jeanetienne It’ll probably easier to make a PR so we can comment on specific lines.

**Comment by brunophilipe** [comment]
The problem is due to the "LetsMove" library using compiler macros to "simplify" the invocation of their localized strings, which breaks Xcode's localization export/import feature completely. I removed that now, and the localization tools should work properly now.

However, there are new strings to be localized now because I added support for the 'Homebrew/bundle' feature. :grin:

**Comment by jeanetienne** [comment]
@brunophilipe 
@bfontaine 

Please see PR at: https://github.com/brunophilipe/Cakebrew/pull/163

Thanks!
