### ISSUE TITLE
Outdated screen: Version installed is shown as the same as the version available 

### ISSUE THREAD

**Issue by iAugur** [brunophilipe/Cakebrew#176]
In the latest OSX version 1.2.1 (build 502) there is a bug in the updates/outdated screen whereby the version installed and the version available are the same until you update the selected formula info.

**Comment by cmsimike** [comment]
![image](https://cloud.githubusercontent.com/assets/204378/18453804/d0455016-78f5-11e6-93fd-821ca6e060ed.png)
This is what I'm getting now in the outdated screen

**Comment by brunophilipe** [comment]
@iAugur I have fixed this bug. The fix will be present in the next release.

@cmsimike I think you have a problem with your brew installation. Try updating brew from the command line and running `brew doctor`. Since your problem is not related to the current issue – which was fixed – I will close the issue.
