### ISSUE TITLE
zsh in CakeBrew doesn't find 'brew' command

### ISSUE THREAD

**Issue by jonphipps** [brunophilipe/Cakebrew#65]
In Cakebrew:

``` bash
zsh:1: command not found: brew
Task finished at 2014-06-05 10:33 AM!
```

In terminal:

``` bash
# jonphipps in ~ [10:34:17]
$ brew update
Updated Homebrew from c6d35b4d to 775680fb.
...
$ which brew
/usr/local/bin/brew
$ brew doctor
Your system is ready to brew.
```

In system log:

```
2014-06-05 10:32:34.937 AM Cakebrew[29826]: User shell: /usr/local/bin/zsh
```

OS X 10.8.5
Also all Formulae counts are 0.

**Comment by gwerbin** [comment]
Not sure if this is still an issue, but hopefully I can shed some light on where to look for solutions.

OSX/MacOS (at least since 10.9 when I switched from Windows 🙊) ships with the following `/etc/zprofile`:

```zsh
# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

As described [here](http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper) and in the man page for `path_helper(1)`, the command `path_helper -s` generates a Bash script that:

1. adds the contents of `/etc/paths` and `/etc/manpaths` to `PATH`
2. iterates over files in `/etc/paths.d` and `/etc/manpaths.d`, appending the contents of each to `PATH`
3. exports `PATH`

which can then be `eval`ed by the shell.

Startup files are loaded in this order: `zshenv`, `zprofile`, `zshrc`, and finally `zlogin`. `/etc/zshenv` is loaded first no matter what. Then, if the `GLOBAL_RCS` option is set (which it is by default) `/etc` is searched for these files. Then if the `RCS` option is set (also "on" by default), `$ZDOTDIR`, or `$HOME` if `ZDOTDIR` is unset. `/zshenv` is always loaded; `zprofile` and `zlogin` are loaded only for login shells, and `zshrc` is loaded only for interactive shells.

Since the shell is non-interactive, `zprofile` and `zlogin` are both loaded and are loaded one after another, so there's no reason to fuss over which one contains what. So these are the files that are being loaded by Cakebrew, if Cakebrew is in fact opening a non-interactive login shell:

1. `/etc/zshenv`; missing by default
2. `/etc/zprofile`; the `path_helper` stuff is here by default
3. `/etc/zlogin`; missing by default
4. `${ZDOTDIR:-HOME}/zshenv`
5. `${ZDOTDIR:-HOME}/zprofile`
6. `${ZDOTDIR:-HOME}/zlogin`

It seems like @jonphipps and the user in #107 have issues in one of these files, or in `/etc/paths`, `/etc/paths.d`, `/etc/manpaths`, `/etc/manpaths.d`.

**Comment by aubreypwd** [comment]
Adding:

```bash
export PATH="/opt/homebrew/bin:$PATH"
```

...to `$HOME/.zlogin` made Cakebrew work for me. I had my `$PATH` setup in `.zshrc` but it still failed to load, I guess Cakebrew just doesn't catch the `.zshrc` file?
